version: '3.8'

services:

  # Datos estructurados
  postgres:
    container_name: postgres_db
    image: postgres:16
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: userGESTDB
      POSTGRES_PASSWORD: passGESTDB
      POSTGRES_DB: GESTDB
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
      - ./postgres/init:/docker-entrypoint-initdb.d
      - ./postgres/csv:/csv # TODO: esto es dummy, luego habrá que insetar datos reales desde los jupyters
    networks:
          - gestbd_net
  pgadmin: 
    image: dpage/pgadmin4
    container_name: pgadmin_db
    restart: always
    ports:
      - 8082:80
    environment:
      PGADMIN_DEFAULT_EMAIL: cinco@GESTDB.com
      PGADMIN_DEFAULT_PASSWORD: cinco
    depends_on:
      - postgres
    volumes:
      - ./postgres/datapga:/tmpdata
      - ./postgres/dataexample:/var/lib/pgadmin/storage
    networks:
          - gestbd_net

  # Datos no estructurados  
  elasticsearch:
    container_name: elasticsearch_db
    image: elasticsearch:8.7.0
    ports:
      - 8000:9200      
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
      - xpack.security.enabled=false
    #volumes:
    #  - ./es-data:/usr/share/elasticsearch/data
    volumes:
      - ./elasticsearch/seed_es.sh:/usr/share/elasticsearch/data/seed_es.sh # TODO: esto es dummy, luego habrá que insetar datos reales desde los jupyters
    networks:
      - gestbd_net
  
  # Datos enlazados 
  graphdb:
    container_name: graphdb_db
    image: ontotext/graphdb:10.3.2
    ports:
      - 8001:7200
    environment:
      GDB_JAVA_OPTS: -Dgraphdb.workbench.importDirectory=/opt/graphdb/home/graphdb-import
    
    volumes:
      - ./graphdb/imports:/opt/graphdb/home/graphdb-import
      - ./graphdb/gd-data:/opt/graphdb/home

    networks:
      - gestbd_net

  # Jupyter Notebooks
  jupyter:
    build: ./jupyter
    container_name: jupyter_lab
    
    ports:
      - 8002:8888
    
    volumes:
      - "./jupyter/src:/home/gestbd/"        

    networks:
      - gestbd_net

  jupyter_llm:
    build: ./jupyter_llm
    container_name: jupyter_llm_lab
    restart: unless-stopped
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    ports:
      - 8003:8003
    volumes:
      - ./jupyter_llm/src:/home/gestbd
      - ollama_models:/root/.ollama

    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility

    networks:
      - gestbd_net

volumes:
  ollama_models:

networks:
    gestbd_net:
      